# Configuration pour l'API OpenWeatherMap
# Obtenez votre clé API gratuite sur : https://openweathermap.org/api
weather.api.key=79f2e054a0d8ea223d4c50292e3c1f1c
weather.default.city=Tunis
weather.units=metric
weather.language=fr
